[package]
name = "render-app"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
slint = "1.11.0"
render-lib = { path = "../render-lib" }

[build-dependencies]
slint-build = "1.11.0"