/*
Page to manage the lights, including delete lights.
*/

import { Light, LightManage } from "../mod/util.slint";
import { Styles } from "../mod/style.slint";

export component ManageLightPage inherits Rectangle {
    // background: transparent;

    VerticalLayout {
        alignment: center;
        padding: 10px;

        for light-obj in LightManage.lights: VerticalLayout {
            vertical-stretch: 0;

            // per light-obj
            HorizontalLayout {
                padding: Styles.sizes.md;
                VerticalLayout {
                    HorizontalLayout {
                        Text {
                            text: light-obj.name;
                            font-size: Styles.sizes.md;
                            font-weight: 400;
                        }
                        Text {
                            text: light-obj.type;
                            font-size: Styles.sizes.md;
                            font-weight: 400;
                            // FIXME: bug that could not find the color style
                            // color: light-obj.type == "Point" ? Styles.light-theme.lightType-point : light-obj.type == "Spot" ? Styles.light-theme.lightType-spot : Styles.light-theme.lightType-directional;
                        }
                    }

                    Text {
                        text: "position";
                        font-size: Styles.sizes.sm;
                        // font-weight: 400;
                    }
                    HorizontalLayout {
                        Text {
                            text: "X: " + light-obj.position-x;
                        }
                        Text {
                            text: "Y: " + light-obj.position-y;
                        }
                        Text {
                            text: "Z: " + light-obj.position-z;
                        }
                    }

                    Text {
                        text: "color(RGB)";
                        font-size: Styles.sizes.sm;
                        // font-weight: 400;
                    }
                    HorizontalLayout {
                        Text {
                            text: "R: " + light-obj.color-R;
                        }
                        Text {
                            text: "G: " + light-obj.color-G;
                        }
                        Text {
                            text: "B: " + light-obj.color-B;
                        }
                    }

                    Text {
                        text: "forward";
                        font-size: Styles.sizes.sm;
                        // font-weight: 400;
                    }
                    HorizontalLayout {
                        Text {
                            text: "X-forward: " + light-obj.position-x;
                        }
                        Text {
                            text: "Y-forward: " + light-obj.position-y;
                        }
                        Text {
                            text: "Z-forward: " + light-obj.position-z;
                        }
                    }
                }
            }

            Rectangle {
                height: 1px;
                background: Styles.light-theme.element-bg;
            }
        }
        Rectangle {
            vertical-stretch: 1;
        }
    }
}