/*
Page to manage the lights, including delete lights.
*/

import { Button } from "std-widgets.slint";
import { Light, LightManage } from "../mod/util.slint";
import { Styles } from "../mod/style.slint";

export component ManageLightPage inherits Rectangle {
    // background: transparent;
    callback load_model();

    VerticalLayout {
        alignment: center;
        padding: 10px;

        for light-obj in LightManage.lights: VerticalLayout {
            vertical-stretch: 0;

            // per light-obj
            HorizontalLayout {
                padding: Styles.sizes.md;
                VerticalLayout {
                    HorizontalLayout {
                        Text {
                            text: light-obj.name;
                            font-size: Styles.sizes.md;
                            font-weight: 400;
                        }
                        Text {
                            text: light-obj.light_type;
                            font-size: Styles.sizes.md;
                            font-weight: 400;
                            // FIXME: bug that could not find the color style
                            // color: light-obj.type == "Spot" ? Styles.light-theme.lightType-point : Styles.light-theme.lightType-directional;
                            color: light-obj.light_type == "Spot" ? Colors.red : Colors.yellowgreen;
                        }
                    }

                    Text {
                        text: "position";
                        font-size: Styles.sizes.sm;
                        // font-weight: 400;
                    }
                    HorizontalLayout {
                        Text {
                            text: "X: " + light-obj.position-x;
                        }
                        Text {
                            text: "Y: " + light-obj.position-y;
                        }
                        Text {
                            text: "Z: " + light-obj.position-z;
                        }
                    }

                    Text {
                        text: "color(RGB)";
                        font-size: Styles.sizes.sm;
                        // font-weight: 400;
                    }
                    HorizontalLayout {
                        Text {
                            text: "R: " + light-obj.color-R;
                        }
                        Text {
                            text: "G: " + light-obj.color-G;
                        }
                        Text {
                            text: "B: " + light-obj.color-B;
                        }
                    }

                    Text {
                        text: "forward";
                        font-size: Styles.sizes.sm;
                        // font-weight: 400;
                    }
                    HorizontalLayout {
                        Text {
                            text: "X-forward: " + light-obj.position-x;
                        }
                        Text {
                            text: "Y-forward: " + light-obj.position-y;
                        }
                        Text {
                            text: "Z-forward: " + light-obj.position-z;
                        }
                    }
                    delete-button := Button {
                        text: "删除";
                        clicked => {
                            LightManage.del_light(light-obj);
                        }
                    }
                }
            }

            Rectangle {
                height: 1px;
                background: Styles.light-theme.element-bg;
            }
        }
        Rectangle {
            vertical-stretch: 1;
        }
        Button {
            text: "load new model";
            width: 80%;
            clicked => {
                load_model();
            }
        }
    }
}