/*
Export object or class
*/

export struct Light {
    name: string,
    // "Spot", "Directional"
    light_type: string,
    position-x: float,
    position-y: float,
    position-z: float,
    color-R: float,
    color-G: float,
    color-B: float,
    forward-x: float,
    forward-y: float,
    forward-z: float,
}

export global LightManage {
    pure callback add_light(lt: Light);
    pure callback del_light(lt: Light);
    in-out property <[Light]> lights;
}
